export const SHOW_MENU = "SHOW_MENU";
export const HIDE_MENU = "HIDE_MENU";

export const SET_LOGIN_USER = "SET_LOGIN_USER";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const ADD_USER_TO_FRIENDS = "ADD_USER_TO_FRIENDS";
export const DELETE_USER_FROM_FRIENDS = "DELETE_USER_FROM_FRIENDS";
export const RESET_USER_DETAILS = "RESET_USER_DETAILS";

export const ADD_GLOBAL_MESSAGE = "ADD_GLOBAL_MESSAGE";
export const LIKE_MESSAGE = "LIKE_MESSAGE";
export const DISLIKE_MESSAGE = "DISLIKE_MESSAGE";
export const LIKE_MESSAGE_DELETE = "LIKE_MESSAGE_DELETE";
export const DISLIKE_MESSAGE_DELETE = "DISLIKE_MESSAGE_DELETE";

export const ADD_NEW_REGISTRED_USER = "ADD_NEW_REGISTRED_USER";
export const UPDATE_USERS_LIST = "UPDATE_USERS_LIST";

export const SET_NOTIFICATION_BAR = "SET_NOTIFICATION_BAR";
export const DELETE_NOTIFICATIONS = "DELETE_NOTIFICATIONS";
