export const SHOW_MENU = "SHOW_MENU";
export const HIDE_MENU = "HIDE_MENU";

export const SET_LOGIN_USER = "SET_LOGIN_USER";
export const SET_USER_DETAILS = "SET_USER_DETAILS";
export const ADD_USER_TO_FRIENDS = "ADD_USER_TO_FRIENDS";
export const DELETE_USER_FROM_FRIENDS = "DELETE_USER_FROM_FRIENDS";
export const RESET_USER_DETAILS = "RESET_USER_DETAILS";
